library(ggplot2)
library(data.table)
library(magrittr)
# ##################
# ### QUESTION 3 ###
# ##################

### RESPONSE NOTES ############################
### The data being generated by 'rnorm(100)' first follows the behavior of a hundred values sampled from a standard normal distribution,
### where by default rnorm sets parameters mean to zero and the standard deviation to 1.  These hundred samples are returned in a numeric 
### vector in R.  After, the cumulative sum indicated by the 'cumsum()' function creates a running total of 
### the hundred samples.  Graphically the function generates the following:
###############################################

## BEGIN ANALYSIS AND GRAPHS
x <- rnorm(100)
y <- x %>% cumsum()
DT <- data.table(x=x, y=y)

DT %>%
  ggplot(aes(x=x, y=y))+
  geom_line()+
  theme_classic()

ggsave(path="./", filename="q3_cumsum_random_walk.png", height = 4.78, width = 8.75, units = "in", device = "png" )
# ggsave(path="./", filename="q3_cumsum_random_walk1.png", height = 4.78, width = 8.75, units = "in", device = "png" )
# ggsave(path="./", filename="q3_cumsum_random_walk2.png", height = 4.78, width = 8.75, units = "in", device = "png" )
# ggsave(path="./", filename="q3_cumsum_random_walk3.png", height = 4.78, width = 8.75, units = "in", device = "png" )
## END ANALYSIS AND GRAPHS


### RESPONSE NOTES (continued) ################
### upon investigating a line graph chart (one example being 'q3_cumsum_random_walk') of the cumulative distribution, the generated data 
### seems to follow a random walk or brownian motion.  Running multiple iterations of 100 samples reveals that the random walk is sensistive
### to initial conditions. Because the distribution looks at first blush multi-modal, we should investigate the long-run statistics of the 
### generated data at higher values of N.  This effort reveals graphs 'q3_cumsum_dist_100' to 'q3_cumsum_dist_100000'.
###############################################


## BEGIN ANALYSIS AND GRAPHS
DT %>%
  ggplot(aes(x=y, y=..count../sum(..count..)))+
  geom_histogram(binwidth=1)+
  theme_classic()

ggsave(path="./", filename="q3_cumsum_dist.png", height = 4.78, width = 8.75, units = "in", device = "png" )
# ggsave(path="./", filename="q3_cumsum_dist_100.png", height = 4.78, width = 8.75, units = "in", device = "png" )
# ggsave(path="./", filename="q3_cumsum_dist_1000.png", height = 4.78, width = 8.75, units = "in", device = "png" )
# ggsave(path="./", filename="q3_cumsum_dist_10000.png", height = 4.78, width = 8.75, units = "in", device = "png" )
# ggsave(path="./", filename="q3_cumsum_dist_100000.png", height = 4.78, width = 8.75, units = "in", device = "png" )
## END ANALYSIS AND GRAPHS


### RESPONSE NOTES (continued) ################
### More generally, we develop a general sense of statistical parameters for the long-run behavior of the generated data as shown in the
### following graphs.
###############################################


## BEGIN ANALYSIS AND GRAPHS
# look at stat params for increasing values of N
N <- 2:1000
list_of_cumsums <- N %>% lapply(rnorm) %>% lapply(cumsum)
mean <- list_of_cumsums %>% lapply(mean) %>% unlist()
std_dev <- list_of_cumsums %>% lapply(sd) %>% unlist()

DT2 <- data.table(N=N, mean=mean, std_dev=std_dev)

DT2 %>%
  ggplot(aes(x=N, y=std_dev))+
  geom_point()+
  geom_smooth()+
  theme_classic()

ggsave(path="./", filename="q3_cumsum_std_dev.png", height = 4.78, width = 8.75, units = "in", device = "png" )

DT2 %>%
  ggplot(aes(x=N, y=mean))+
  geom_point()+
  geom_smooth()+
  theme_classic()

ggsave(path="./", filename="q3_cumsum_mean.png", height = 4.78, width = 8.75, units = "in", device = "png" )

## END ANALYSIS AND GRAPHS


### RESPONSE NOTES (continued) ################
### In viewing the means and standard deviations with respect to increasing N according to graphs 'q3_cumsum_mean' and 'q3_cumsum_std_dev',
### respectively, it looks like the long run statistics of the generated data yields a mean that stabilizes around zero, but has INCREASING 
### variance.
###############################################

